import assert from 'node:assert/strict';
import { initialSale, saleReducer, saleTotals, saleInvoice, totalsFor, invoices } from '../src/demo-data.mjs';

assert.deepEqual(totalsFor('2026-10'), { revenue: 82000, purchases: 48000, receivables: 26400, payables: 9600, cash: 24000 });
assert.deepEqual(totalsFor('2026-09'), { revenue: 60000, purchases: 35000, receivables: 6000, payables: 6000, cash: 30000 });
let sale = initialSale();
sale = saleReducer(sale, { type: 'next' });
assert.equal(sale.approvedVersion, 1);
sale = saleReducer(sale, { type: 'quantity', value: 12 });
assert.equal(sale.stage, 0, 'La modification du devis impose un nouvel accord');
assert.equal(sale.approvedVersion, null);
assert.equal(sale.version, 2);
assert.equal(saleReducer(sale, { type: 'quantity', value: 101 }), sale, 'Le devis ne peut dépasser le stock');
assert.equal(saleReducer(sale, { type: 'quantity', value: 0 }), sale);
sale = saleReducer(sale, { type: 'next' });
sale = saleReducer(sale, { type: 'next' });
assert.equal(saleReducer(sale, { type: 'quantity', value: 8 }), sale, 'Une commande ne se modifie pas comme un devis');
sale = saleReducer(sale, { type: 'next' });
assert.deepEqual(saleTotals(sale), { ht: 3000, tax: 600, ttc: 3600, physical: 100, reserved: 12, available: 88 });
sale = saleReducer(sale, { type: 'next' });
assert.equal(saleTotals(sale).physical, 88);
assert.equal(saleTotals(sale).reserved, 0);
assert.equal(saleTotals(sale).available, 88);
assert.equal(saleInvoice(sale).length, 0, 'La livraison ne crée pas implicitement une facture');
sale = saleReducer(sale, { type: 'next' });
assert.equal(totalsFor('2026-10', [...invoices, ...saleInvoice(sale)]).revenue, 85000);
assert.equal(totalsFor('2026-10', [...invoices, ...saleInvoice(sale)]).receivables, 30000);
sale = saleReducer(sale, { type: 'next' });
assert.equal(totalsFor('2026-10', [...invoices, ...saleInvoice(sale)]).receivables, 26400);
assert.equal(totalsFor('2026-10', [...invoices, ...saleInvoice(sale)]).cash, 27600);
assert.equal(saleReducer(sale, { type: 'next' }), sale, 'Pas de paiement dupliqué');
assert.deepEqual(saleReducer(sale, { type: 'reset' }), initialSale());
console.log('Démo : réconciliation financière, version du devis, stock, paiement et remise à zéro vérifiés.');
