import { applyRefonte } from './content-refonte.mjs';
import { plainCopy } from './copy.mjs';
import { searchAnswers, guideLinks } from './search-content.mjs';
export const pageContent = {
  "/produit/": {
    title: "Le logiciel Gestelyo | Ventes, achats, stocks et pilotage", description: "Découvrez les parcours Gestelyo : suivi client, devis, facturation, achats et stocks. Explorez le produit à travers des exemples concrets.", eyebrow: "LE PRODUIT", heading: "Du premier contact au paiement.", intro: "Votre activité avance par étapes. Gardez le lien entre vos clients, vos documents commerciaux, vos marchandises et vos règlements.", layout: "product",
    sections: [
      ["Préparer une vente", "Retrouvez le client, les produits ou prestations et les informations utiles à votre proposition. L’objectif : préparer un devis dans son contexte, sans reconstruire l’historique de la relation."],
      ["Organiser la commande", "Une fois la proposition acceptée, suivez les étapes de traitement. Documents, préparation et facturation font partie d’un même parcours de gestion."],
      ["Garder une vision sur les paiements", "Distinguez les factures réglées, les échéances à venir et les montants à suivre. Retrouvez le document concerné avant de préparer votre prochaine action."],
      ["Une place utile pour l’intelligence artificielle", "Préparer un document, rédiger un message ou expliquer un indicateur : les usages IA envisagés partent d’une tâche concrète. Les fonctions disponibles, leurs quotas et les étapes de validation seront documentés avant leur commercialisation."],
    ], question: ["Puis-je tester le produit ?", "La démonstration interactive permet de naviguer dans les vues, rechercher une commande et consulter son détail. Elle utilise des données fictives ; elle ne crée pas de compte ERP réel."], related: ["/demo/", "/modules/", "/tarifs/"],
  },
  "/modules/": {
    title: "Modules Gestelyo | CRM, ventes, achats, stock et projets", description: "Explorez les modules Gestelyo : relation client, ventes, achats, stocks, suivi financier et projets dans un même environnement.", eyebrow: "LES MODULES", heading: "Chaque métier. Une même information.", intro: "Gestelyo est un projet de logiciel de gestion intégré pour les PME. Ses modules organisent les informations autour des clients, commandes et projets de votre entreprise.", layout: "modules",
    sections: [["CRM · garder le contexte", "Contacts, échanges et opportunités : retrouvez les informations nécessaires à votre prochaine action commerciale."], ["Ventes · suivre vos documents", "Reliez les devis, commandes, livraisons et factures au client concerné."], ["Achats · organiser les approvisionnements", "Retrouvez les fournisseurs, commandes et réceptions attendues."], ["Stock · comprendre vos disponibilités", "Suivez les entrées, sorties et quantités. Le périmètre multi-entrepôts est proposé dans Business."], ["Suivi financier · lire les mouvements", "Rassemblez les recettes, dépenses et échéances. Ce suivi ne constitue pas une comptabilité réglementaire complète."], ["Projets · suivre les engagements", "Rapprochez documents, dépenses et revenus pour comprendre l’avancement d’une mission."]], question: ["Quels modules sont inclus dans mon abonnement ?", "Les forfaits Essentiel, Business et Premium présentent des périmètres progressifs. Consultez les tarifs pour comparer les utilisateurs inclus et les fonctionnalités proposées au lancement."], related: ["/modules/ventes-facturation/", "/modules/gestion-stock/", "/tarifs/"],
  },
  "/modules/ventes-facturation/": {
    title: "Gestion des devis et factures pour PME | Gestelyo", description: "Organisez vos devis, commandes et factures avec Gestelyo. Retrouvez les documents de chaque client et suivez les paiements associés.", eyebrow: "VENTES & FACTURATION", heading: "Gardez le fil de chaque vente.", intro: "Une facture prend son sens dans une relation client. Retrouvez le contexte de vos documents commerciaux, de la proposition au suivi du paiement.", layout: "sales",
    sections: [["Préparer un devis", "Retrouvez les coordonnées du client, les produits ou prestations concernés et les conditions de votre proposition. Gardez les informations utiles à portée de main."], ["Comprendre où en est la vente", "Identifiez les propositions en préparation, les opérations acceptées et les documents à facturer. Le parcours visé relie chaque étape à son contexte."], ["Suivre les montants à encaisser", "Consultez les échéances et les règlements enregistrés pour préparer votre suivi client. L’historique du document aide à choisir la prochaine action."]], question: ["Gestelyo propose-t-il la facturation électronique ?", "Les capacités de facturation électronique et les connexions réglementaires seront précisées lorsqu’elles seront validées. Aucune certification ni conformité spécifique n’est annoncée à ce stade."], related: ["/produit/", "/demo/", "/tarifs/"],
  },
  "/modules/gestion-stock/": {
    title: "Gestion de stock pour PME et distributeurs | Gestelyo", description: "Découvrez le suivi des stocks Gestelyo : disponibilités, entrées, sorties et organisation des entrepôts selon votre abonnement.", eyebrow: "GESTION DE STOCK", heading: "Savoir ce qui est disponible. Avant de s’engager.", intro: "Une vente, une réception ou un transfert modifie vos disponibilités. Le module Stock vise à réunir ces mouvements dans une lecture commune.", layout: "stock",
    sections: [["Retrouver les quantités", "Consultez les informations d’un article pour préparer une vente ou organiser votre prochain achat. Distinguez les quantités physiques des quantités déjà engagées."], ["Comprendre les mouvements", "Retrouvez les entrées et sorties associées à votre activité. Identifiez l’opération à l’origine d’un changement de quantité."], ["Organiser plusieurs lieux de stockage", "Business est le forfait proposé pour le périmètre multi-entrepôts. Le nombre d’entrepôts et les règles de transfert seront précisés avant souscription."]], question: ["Quel forfait envisager pour plusieurs entrepôts ?", "Le périmètre Business prévoit le suivi multi-entrepôts. La démonstration actuelle illustre l’organisation de l’interface, sans synchronisation avec un stock réel."], related: ["/secteurs/commerce-distribution/", "/ressources/stock-disponible-reserve-physique/", "/tarifs/"],
  },
  "/secteurs/": {
    title: "Gestelyo pour les services, le commerce et la distribution", description: "Découvrez les usages Gestelyo pour les agences, entreprises de services, commerçants et distributeurs. Choisissez selon vos besoins de gestion.", eyebrow: "VOTRE ACTIVITÉ", heading: "Les bonnes informations pour votre métier.", intro: "Une agence suit des prestations et des projets. Un distributeur suit des marchandises et leurs mouvements. Les priorités changent ; le besoin de coordination reste.", layout: "sectors",
    sections: [["Services & agences", "Retrouvez vos clients, vos propositions et les documents de chaque mission. Le suivi de projet vise à relier les engagements aux dépenses et revenus."], ["Commerce & distribution", "Coordonnez commandes clients, achats fournisseurs et disponibilités. Gardez une lecture des marchandises et des paiements."]], question: ["Le secteur détermine-t-il le prix ?", "Les abonnements Gestelyo sont organisés par forfait : Essentiel, Business et Premium. Le choix dépend des fonctionnalités et du nombre d’utilisateurs, plutôt que du seul secteur d’activité."], related: ["/secteurs/services-agences/", "/secteurs/commerce-distribution/", "/tarifs/"],
  },
  "/secteurs/services-agences/": {
    title: "Logiciel de gestion pour agences et services | Gestelyo", description: "Structurez vos clients, devis, projets et paiements. Découvrez le périmètre Gestelyo proposé aux agences et entreprises de services.", eyebrow: "SERVICES & AGENCES", heading: "Chaque client. Chaque mission. Le contexte complet.", intro: "Votre équipe doit savoir ce qui a été proposé, accepté, réalisé et facturé. Réunissez ces informations autour de vos clients et de vos projets.", layout: "services",
    sections: [["Préparer vos propositions", "Retrouvez les devis associés à un client et les prochaines actions commerciales. Conservez le contexte utile lorsque plusieurs personnes interviennent."], ["Relier le projet à ses documents", "Gardez une lecture des engagements, dépenses et revenus d’une mission. Le périmètre proposé vise à comprendre ce qui a été prévu et ce qui a été réalisé."], ["Choisir votre forfait", "Essentiel couvre le périmètre commercial de base. Business est proposé pour les besoins de suivi de projets, permissions et rapports avancés."]], question: ["Comment la rentabilité d’une prestation sera-t-elle suivie ?", "Le suivi envisagé rapproche les coûts et les revenus d’un projet. Les méthodes de calcul et les données prises en compte seront documentées avant commercialisation."], related: ["/modules/ventes-facturation/", "/ressources/marge-et-chiffre-affaires/", "/tarifs/"],
  },
  "/secteurs/commerce-distribution/": {
    title: "Logiciel de gestion pour commerce et distribution | Gestelyo", description: "Reliez ventes, achats et stocks avec Gestelyo. Découvrez le périmètre proposé aux commerçants, négociants et distributeurs.", eyebrow: "COMMERCE & DISTRIBUTION", heading: "Ce que vous achetez. Ce que vous vendez. Une seule vision.", intro: "Vos disponibilités dépendent des marchandises, des commandes et des approvisionnements. Gestelyo vise à réunir ces informations pour coordonner votre équipe.", layout: "distribution",
    sections: [["Préparer les ventes avec le stock", "Consultez les disponibilités et retrouvez les opérations associées à vos articles. L’objectif est de prendre un engagement commercial avec le contexte nécessaire."], ["Suivre les approvisionnements", "Identifiez les commandes fournisseurs et les réceptions attendues. Reliez les achats à vos besoins de marchandises."], ["Coordonner les entrepôts", "Business est le forfait proposé pour le suivi multi-entrepôts et les besoins de coordination d’équipe. Consultez son périmètre avant de définir votre configuration."]], question: ["Gestelyo gère-t-il plusieurs sociétés ?", "Le fonctionnement multi-sociétés ne fait pas partie du périmètre validé à ce stade. Un besoin de ce type nécessite une définition spécifique."], related: ["/modules/gestion-stock/", "/ressources/stock-disponible-reserve-physique/", "/tarifs/"],
  },
  "/tarifs/": {
    title: "Tarifs Gestelyo | Abonnements mensuels et annuels", description: "Comparez Essentiel, Business et Premium : dès 450 DH HT/mois ou 5 130 DH HT/an. Découvrez les utilisateurs inclus et les modalités de paiement.", eyebrow: "LES ABONNEMENTS", heading: "Une gestion commune. Un prix clair.", intro: "Trois forfaits, deux rythmes de paiement.", layout: "pricing", sections: [], related: ["/produit/", "/demo/", "/contact/"],
  },
  "/ressources/": {
    title: "Guides de gestion pour PME | Ressources Gestelyo", description: "Des guides concrets sur les devis, les paiements, les stocks et le choix d’un logiciel de gestion pour votre PME.", eyebrow: "LES RESSOURCES", heading: "Comprendre vos chiffres. Préparer vos décisions.", intro: "Des explications et des exemples pour organiser votre gestion. Choisissez une question et repartez avec une méthode à appliquer.", layout: "resources", sections: [], related: ["/produit/", "/tarifs/"],
  },
  "/a-propos/": {
    title: "À propos de Gestelyo | Notre approche de la gestion PME", description: "Découvrez le projet Gestelyo : rendre les informations de gestion plus accessibles aux dirigeants et aux équipes de petites et moyennes entreprises.", eyebrow: "À PROPOS", heading: "Une équipe avance avec une information commune.", intro: "Comment retrouver le contexte d’une opération lorsque ses informations vivent dans plusieurs fichiers, documents et conversations ? C’est le point de départ de Gestelyo.", layout: "about",
    sections: [["Partir du travail quotidien", "Préparer une vente, recevoir une commande, suivre un paiement : notre ambition est de concevoir les parcours autour des opérations qui font avancer une entreprise."], ["Rendre les informations lisibles", "Présenter les données dans leur contexte, avec des libellés compréhensibles et des actions identifiables. La clarté du produit doit aider chaque personne à retrouver sa place dans le travail collectif."], ["Où en est le projet ?", "Gestelyo dispose d’une démonstration interactive. Le périmètre commercial, les intégrations et les conditions de disponibilité restent à confirmer. Vous pouvez contacter l’équipe à omarsoubaibi@gestelyo.com ou redachouikh@gestelyo.com. L’identité juridique de l’éditeur sera publiée avant l’ouverture du service."]], related: ["/demo/", "/securite/", "/contact/"],
  },
  "/securite/": {
    title: "Sécurité et protection des données | Gestelyo", description: "Consultez le statut des informations de sécurité Gestelyo : accès, hébergement, sauvegardes et récupération des données.", eyebrow: "SÉCURITÉ & DONNÉES", heading: "Comprendre avant de confier vos données.", intro: "Choisir un logiciel de gestion implique de savoir où les données sont conservées, qui peut y accéder et comment les récupérer. Ces informations seront documentées avant l’ouverture du service.", layout: "security",
    sections: [["Accès et permissions", "Les rôles, méthodes d’authentification et permissions du service final sont en cours de définition. Aucun compte ERP réel n’est créé depuis la démonstration."], ["Hébergement et sauvegardes", "Le prestataire, les localisations, les durées de conservation et la procédure de restauration du service final ne sont pas encore publiés. Aucune certification ou garantie de disponibilité n’est annoncée."], ["Récupération des données", "Les formats d’export et les conditions de suppression seront précisés avant la souscription. La démonstration actuelle utilise des données fictives et ne persiste pas les actions dans un serveur ERP."]], question: ["La démonstration contient-elle des données clients ?", "Non. Les entreprises, commandes, montants et variations sont fictifs. Ils servent à illustrer l’interface."], related: ["/a-propos/", "/demo/", "/contact/"],
  },
  "/contact/": {
    title: "Contacter Gestelyo | Préparer votre projet de gestion", description: "Contactez Gestelyo à omarsoubaibi@gestelyo.com ou redachouikh@gestelyo.com pour échanger sur votre projet de gestion.", eyebrow: "VOTRE PROJET", heading: "Parlons de votre façon de travailler.", intro: "Ventes, achats, stocks : commencez par les opérations que vous souhaitez améliorer. Écrivez directement à l’équipe ou préparez un résumé de votre besoin ci dessous.", layout: "contact", sections: [["Un échange qui part de votre quotidien", "Quels outils utilisez-vous ? Qui doit accéder aux informations ? Où perdez-vous le contexte ? Ces questions aident à définir le périmètre utile à votre entreprise."]], related: ["/demo/", "/tarifs/"],
  },
  "/demo/": {
    title: "Démo Gestelyo | Explorer le tableau de bord ERP", description: "Explorez le prototype Gestelyo : tableau de bord, commandes et modules. Démonstration interactive en français avec données fictives.", eyebrow: "LA DÉMONSTRATION", heading: "Prenez les commandes.", intro: "Explorez le prototype à votre rythme.", layout: "demo", sections: [], related: [],
  },
};

applyRefonte(pageContent);

export const articles = [
  { slug: "du-devis-au-paiement", name: "Du devis au paiement : organiser votre suivi commercial", category: "Ventes", description: "Les étapes, documents et informations à partager entre les membres de votre équipe.", sections: [["Un parcours, plusieurs étapes", "Commencez par définir les étapes que votre équipe utilise réellement : proposition, accord, commande, livraison, facture et paiement. Une prestation de service n’a pas forcément le même parcours qu’une vente de marchandises."], ["Le contexte à transmettre", "À chaque passage, conservez la référence du document précédent, la personne responsable et l’action attendue. Un accord client doit rester accessible à la personne qui prépare la facture."], ["Un contrôle simple chaque semaine", "Passez en revue les devis sans réponse, les commandes à traiter et les factures non réglées. Pour chaque ligne, attribuez une prochaine action et une personne responsable."]]},
  { slug: "stock-disponible-reserve-physique", name: "Stock disponible, réservé et physique : comprendre la différence", category: "Stocks", description: "Trois notions à distinguer avant de confirmer une commande ou de préparer un inventaire.", sections: [["Le stock physique", "Le stock physique correspond aux quantités réellement présentes. Un inventaire sert à comparer ce comptage à la quantité enregistrée dans votre outil."], ["Le stock réservé", "Le stock réservé est affecté à une commande ou à un besoin identifié. Il peut encore être physiquement présent tout en étant engagé pour un client."], ["Un exemple de disponibilité", "Exemple fictif : 100 unités sont présentes et 30 sont réservées. Sans autre restriction, 70 restent disponibles à la vente. Les produits bloqués, en quarantaine ou endommagés doivent aussi être pris en compte si votre organisation les distingue."], ["Ce qu’il faut définir en équipe", "Décidez à quel moment une commande réserve le stock et comment une annulation libère cette réservation. Appliquez la même règle à chaque entrepôt."]]},
  { slug: "suivre-les-factures-impayees", name: "Suivre les factures impayées sans perdre le contexte client", category: "Paiements", description: "Organisez les échéances et préparez les informations nécessaires à une relance.", sections: [["Construire une vue des échéances", "Rassemblez la référence de facture, la date d’échéance, le montant restant à payer et le contact chargé du règlement. Vérifiez les paiements partiels avant toute relance."], ["Comprendre la situation", "Une facture manquante, un désaccord sur une livraison et un délai de traitement demandent des réponses différentes. Conservez les échanges pour adapter votre prochaine action."], ["Préparer un message précis", "Rappelez le document, l’échéance et le solde. Demandez si un élément empêche le règlement et notez la réponse. Ce guide décrit une méthode de suivi opérationnel, pas une procédure juridique de recouvrement."]]},
  { slug: "marge-et-chiffre-affaires", name: "Marge et chiffre d’affaires : deux indicateurs, deux questions", category: "Pilotage", description: "Un exemple chiffré pour comprendre ce que chaque indicateur permet d’observer.", sections: [["Ce que mesure le chiffre d’affaires", "Pour ce guide, le chiffre d’affaires correspond au montant hors taxes des ventes retenues sur une période. Il ne correspond pas nécessairement aux sommes encaissées pendant cette même période."], ["Un calcul de marge commerciale", "Exemple fictif simplifié : une marchandise est vendue 1 000 DH HT et son coût d’achat retenu est de 700 DH HT. La marge commerciale de cette vente est de 300 DH. Les autres charges de l’entreprise ne sont pas déduites dans cet exemple."], ["Taux de marge et taux de marque", "Avec ces mêmes chiffres, le taux de marge est 300 ÷ 700, soit environ 42,86 %. Le taux de marque est 300 ÷ 1 000, soit 30 %. Indiquez toujours le dénominateur pour éviter les confusions."], ["Comparer des périodes cohérentes", "Conservez le même périmètre de coûts et la même période lorsque vous comparez vos indicateurs. Ce calcul pédagogique ne remplace pas votre suivi comptable."]]},
  { slug: "choisir-logiciel-gestion", name: "Choisir un logiciel de gestion pour une petite équipe", category: "Organisation", description: "Périmètre, utilisateurs, reprise des données et coût total : les critères à examiner.", sections: [["Partir de trois opérations", "Choisissez les trois opérations qui posent le plus de difficultés aujourd’hui. Préparez un exemple réel de chaque parcours pour vos démonstrations, en retirant les données confidentielles inutiles."], ["Comparer le coût total", "Additionnez l’abonnement, les utilisateurs supplémentaires, les options, la mise en route et les intégrations nécessaires. Comparez une même durée et un même effectif."], ["Vérifier la sortie autant que l’entrée", "Demandez quels formats sont importables et exportables. Vérifiez les conditions de récupération des données, de renouvellement et d’accompagnement avant de choisir."], ["Faire essayer les personnes concernées", "Un décideur, une personne commerciale et une personne chargée du suivi peuvent repérer des besoins différents. Faites tester les parcours qui les concernent."]]},
  { slug: "preparer-vos-donnees", name: "Préparer vos données avant de changer d’outil", category: "Mise en route", description: "Vérifiez vos fichiers clients, fournisseurs et produits avant leur import.", sections: [["Définir ce qui doit être repris", "Séparez les contacts, produits, soldes et documents historiques. Déterminez les informations nécessaires au démarrage plutôt que de reprendre tous les fichiers sans tri."], ["Nettoyer les références", "Identifiez les doublons, les champs manquants et les références incohérentes. Désignez une personne responsable de la validation de chaque fichier."], ["Tester sur un petit échantillon", "Importez d’abord un échantillon représentatif dans un environnement adapté. Contrôlez les correspondances de colonnes, les montants, les dates et les caractères accentués avant d’élargir."], ["Conserver une copie de départ", "Gardez une copie datée des données sources et documentez les corrections apportées. Cette trace aide à expliquer les écarts pendant la transition."]]},
];

for (const article of articles) {
  pageContent[`/ressources/${article.slug}/`] = { title: `${article.name} | Gestelyo`, description: article.description, eyebrow: `GUIDE · ${article.category.toUpperCase()}`, heading: article.name, intro: article.description, layout: "article", sections: article.sections, related: ["/ressources/", "/modules/", "/demo/"] };
}

export const normalizePath = (path) => path === "/" ? "/" : `${path.replace(/\/+$/, "")}/`;
for (const [path, answer] of Object.entries(searchAnswers)) {
  if (!pageContent[path]) continue;
  pageContent[path].answer = answer;
  pageContent[path].related = [...new Set([...pageContent[path].related, ...(guideLinks[path] || [])])];
}
for (const page of Object.values(pageContent)) {
  for (const key of ['title', 'description', 'eyebrow', 'heading', 'intro', 'status']) if (page[key]) page[key] = plainCopy(page[key]);
  for (const key of ['question', 'example']) if (page[key]) page[key] = page[key].map(plainCopy);
  page.sections = page.sections.map(section => section.map(plainCopy));
}
for (const article of articles) {
  article.name = plainCopy(article.name);
  article.description = plainCopy(article.description);
}
export const routeMeta = {
  "/": { title: "Gestelyo | Logiciel de gestion pour PME au Maroc", description: "Découvrez Gestelyo : clients, devis, factures, achats et stocks dans un même espace. Comparez les abonnements et explorez la démonstration." },
  ...pageContent,
};
