const page = (title, description, eyebrow, heading, intro, sections, question, related, extra = {}) => ({ title, description, eyebrow, heading, intro, sections, question, related, layout: 'editorial', status: 'Périmètre prévu · service en développement', ...extra });
export const refonteContent = {
  '/modules/crm/': page('CRM pour PME au Maroc | Clients et suivi commercial Gestelyo', 'Découvrez le CRM Gestelyo : contexte client, documents commerciaux, filtres et suivi d’équipe. Essayez la vue Clients avec des données fictives.', 'RELATION CLIENT · CRM', 'Une fiche client. Toute la relation.', 'Un nom dans un fichier ne suffit pas. Retrouvez les documents et les éléments de contexte nécessaires pour préparer votre prochaine action.', [
    ['Un portefeuille que l’on peut lire', 'Distinguez les clients actifs, les prospects et les relations en pause. Le périmètre visé réunit contacts, ville, responsable commercial et documents associés, avec des accès adaptés à chaque rôle.'],
    ['Retrouver le document avant de relancer', 'Une facture partiellement réglée ne se suit pas comme une facture sans paiement. Rapprochez le TTC facturé et les règlements enregistrés avant de préparer votre échange. Les filtres ne doivent pas masquer le contexte de la relation.'],
    ['Ce que vous pouvez essayer', 'Dans la démonstration, recherchez un client, combinez les filtres statut, ville et commercial, consultez sa fiche et exportez une sélection CSV. Ces actions portent uniquement sur six entreprises fictives ; elles ne synchronisent aucun fichier client réel.'],
  ], ['Les contacts sont-ils partagés entre sociétés ?', 'La cible multi-société nécessite des règles de visibilité et de séparation des données. Les modalités et limites ne sont pas encore validées ; aucun partage illimité n’est annoncé.'], ['/demo/', '/modules/ventes-facturation/', '/migration/'], { status: 'Vue Clients démontrable · CRM complet prévu', example: ['Un contexte concret', 'Atlas Distribution : une facture réglée en octobre et un devis en préparation. La fiche regroupe les documents ; le statut commercial du client reste distinct du statut de paiement.'] }),
  '/modules/achats/': page('Gestion des achats et fournisseurs pour PME | Gestelyo', 'Organisez commandes fournisseurs, réceptions et échéances avec Gestelyo. Découvrez le périmètre achats prévu pour le commerce et la distribution.', 'ACHATS & APPROVISIONNEMENTS', 'Acheter avec les besoins en vue.', 'Une commande fournisseur engage un budget et prépare une réception. Reliez ces deux événements à vos besoins de marchandises.', [
    ['Préparer la commande fournisseur', 'Rapprochez les articles, leurs références fournisseurs, les quantités attendues et les conditions négociées. La cible est de garder une trace de la décision d’achat, plutôt que de traiter la facture comme le seul point de départ.'],
    ['Recevoir et vérifier les quantités', 'Le parcours prévu distingue commande et réception. Une livraison partielle doit laisser une quantité attendue, et un écart doit pouvoir être expliqué avant d’actualiser les disponibilités. Les transferts entre entrepôts relèvent du périmètre avancé.'],
    ['Séparer réception et règlement', 'Une marchandise reçue n’est pas forcément payée. Le suivi financier doit conserver la facture fournisseur, les échéances et les règlements. La démo affiche des achats fictifs dans les indicateurs ; elle ne permet pas encore de créer une commande fournisseur.'],
  ], ['Les achats déclenchent-ils automatiquement un paiement ?', 'Non dans la démonstration. Dans le périmètre envisagé, les paiements restent soumis à une validation humaine et à des autorisations explicites.'], ['/modules/gestion-stock/', '/modules/finance/', '/secteurs/commerce-distribution/'], { example: ['Une réception partielle', 'Sur 50 unités commandées, 30 sont reçues : 20 restent attendues. Le stock physique ne doit augmenter que des 30 unités effectivement acceptées. Cet exemple décrit le fonctionnement cible.'] }),
  '/modules/finance/': page('Finance opérationnelle pour PME | Échéances et flux Gestelyo', 'Comprenez les créances, dettes et flux de trésorerie dans Gestelyo. Finance opérationnelle et exports comptables prévus ; comptabilité native ultérieure.', 'FINANCE OPÉRATIONNELLE', 'Vos échéances méritent une vue claire.', 'Comprendre ce qui reste à encaisser, ce qui reste à payer et ce qui a réellement été réglé. Trois lectures complémentaires de votre activité.', [
    ['Facturé ne veut pas dire encaissé', 'Le chiffre d’affaires de la démo correspond aux factures HT de la période. Les créances correspondent à leur montant TTC moins leurs règlements. Les filtres portent sur une même période pour rendre ces montants conciliables.'],
    ['Lire les flux sans les confondre avec le solde bancaire', 'Le flux net de la démonstration est la différence entre règlements clients et fournisseurs de la période. Il n’intègre pas un solde d’ouverture, une synchronisation bancaire ni toutes les charges de l’entreprise. Il ne représente donc pas le solde disponible d’un compte.'],
    ['Préparer le travail comptable', 'Le lancement vise la finance opérationnelle et des exports dont les formats seront validés avec les outils concernés. La comptabilité native complète appartient à une étape ultérieure. Aucune certification ni conformité fiscale spécifique n’est annoncée.'],
  ], ['Gestelyo remplace-t-il mon logiciel comptable ?', 'Ce remplacement n’est pas annoncé au lancement. Le périmètre cible permet d’organiser les informations de gestion et de préparer leur transmission ; les formats et compatibilités d’export restent à valider.'], ['/demo/', '/integrations/', '/ressources/marge-et-chiffre-affaires/'], { example: ['Une facture, deux montants', 'Une facture de 15 000 DH HT représente 18 000 DH TTC avec la TVA pédagogique de 20 %. Après 12 000 DH de règlement, sa créance restante est de 6 000 DH TTC. Ce taux est un choix de l’exemple, pas une règle fiscale universelle.'] }),
  '/intelligence-artificielle/': page('IA de gestion pour PME | Modes et validation humaine Gestelyo', 'Découvrez les usages IA envisagés dans Gestelyo : assistant, actions contrôlées et automatisation avancée. Paiements et opérations sensibles sous contrôle humain.', 'INTELLIGENCE ARTIFICIELLE', 'Une aide contextualisée. Une décision qui reste la vôtre.', 'L’IA envisagée intervient dans une opération précise : expliquer une variation, préparer un document ou proposer une action. La démonstration actuelle n’est connectée à aucun modèle IA.', [
    ['Mode assistant · comprendre et préparer', 'Le premier mode cible produit une explication ou un brouillon à partir des informations autorisées. Une relance proposée doit rappeler la facture et son solde, puis rester disponible pour relecture. Un texte préparé n’est pas un message envoyé.'],
    ['Mode contrôlé · proposer avant d’exécuter', 'Le second mode prévoit une proposition d’action accompagnée de son contexte et de ses effets. La personne autorisée vérifie et approuve avant exécution. Une modification du document doit rendre l’approbation précédente caduque.'],
    ['Mode avancé · limiter et tracer', 'Les automatisations futures devront respecter un périmètre, des autorisations et une trace des actions. Les paiements, modifications de coordonnées bancaires, droits d’administration et décisions liées à l’emploi conservent une validation humaine obligatoire. Les quotas, tarifs et fonctions par forfait seront précisés avant ouverture.'],
  ], ['L’intelligence artificielle est-elle disponible ou illimitée ?', 'Non. Les modes décrits constituent une cible produit. Aucun accès IA réel ni usage illimité n’est proposé dans cet aperçu ; les capacités et quotas seront publiés après validation.'], ['/personnalisation/', '/securite/', '/demo/'], { example: ['Le contrôle, visible dans la démo', 'L’accord du devis porte sur une version précise. Changez sa quantité après accord : le parcours exige un nouvel accord avant création de la commande. Ce contrôle est déterministe et ne repose pas sur une IA.'] }),
  '/integrations/': page('Intégrations et échanges de données ERP | Gestelyo', 'Préparez les échanges entre Gestelyo et vos outils : formats, API et responsabilités. Consultez le statut des connexions envisagées avant de choisir.', 'INTÉGRATIONS', 'Relier les outils commence par définir les échanges.', 'Quelles données doivent circuler, dans quel sens et sous quelle responsabilité ? Ces questions précèdent le choix d’un connecteur.', [
    ['Définir la source de référence', 'Un client, un article ou un règlement ne doit pas avoir deux versions concurrentes. Pour chaque échange, identifiez l’outil responsable de la donnée, la fréquence de synchronisation et la gestion des doublons.'],
    ['Vérifier un format avant de promettre une connexion', 'Les échanges CSV, les exports comptables et les API font partie du périmètre à étudier. Manageo, Odoo, Sage et EBP sont des outils potentiellement concernés par des reprises ou échanges ; leur mention n’établit ni partenariat ni connecteur livré. Les versions et formats doivent être vérifiés au cas par cas.'],
    ['Prévoir les erreurs et les accès', 'Un échange fiable doit expliquer les refus, permettre de reprendre une opération sans doublon et limiter les droits techniques. Les transporteurs et prestataires externes seront à configurer avec les contrats et comptes de votre entreprise ; aucun contrat de transport n’est inclus implicitement.'],
  ], ['Existe-t-il déjà des connecteurs prêts à activer ?', 'Aucun connecteur opérationnel n’est livré dans la démonstration. Une connexion ne sera annoncée comme disponible qu’après validation de son périmètre, de ses versions et de son fonctionnement.'], ['/migration/', '/modules/finance/', '/securite/']),
  '/migration/': page('Migration de données vers un ERP PME | Préparer Gestelyo', 'Préparez une reprise de clients, articles et soldes vers Gestelyo : inventaire, nettoyage, test et contrôle. Aucun import réel dans la démonstration.', 'MISE EN ROUTE · DONNÉES', 'Repartir avec les bonnes données.', 'Changer d’outil est l’occasion de retrouver des références fiables. La reprise se prépare fichier par fichier, avec un contrôle à chaque étape.', [
    ['Inventorier ce qui sera repris', 'Séparez clients, fournisseurs, articles, stocks et soldes. Identifiez les historiques réellement utiles au démarrage et les pièces à conserver dans l’ancien outil. Définissez une date de bascule et une personne qui valide chaque périmètre.'],
    ['Nettoyer puis tester un échantillon', 'Repérez les doublons, références absentes, montants incohérents et colonnes ambiguës. Sur un échantillon, contrôlez accents, dates, unités, taxes et correspondances de champs. Une extension de fichier ne garantit pas à elle seule un import compatible.'],
    ['Réconcilier avant la bascule', 'Comparez le nombre de lignes, les totaux, les soldes et les quantités entre source et destination. Conservez les sources et un journal des corrections. La démonstration ne reçoit aucun fichier réel ; l’assistance, les formats et les coûts de reprise restent à définir.'],
  ], ['Puis-je migrer depuis Excel, Manageo, Odoo, Sage ou EBP ?', 'Une étude des exports, de la version et des données est nécessaire. Aucun import universel ni reprise automatique de tous les historiques n’est garanti. Commencez par préparer un inventaire et un échantillon anonymisé.'], ['/ressources/preparer-vos-donnees/', '/integrations/', '/contact/'], { example: ['Un contrôle simple', 'Votre source compte 250 articles et 1 200 unités physiques. Après un essai, contrôlez ces deux totaux, puis vérifiez quelques articles avec réservations ou unités particulières. Un total juste ne suffit pas à prouver que chaque ligne est correcte.'] }),
  '/mobile-pos/': page('Mobile et point de vente pour PME | Feuille de route Gestelyo', 'Découvrez les usages mobile et POS prévus pour Gestelyo : consultation terrain et point de vente. Applications et mode hors ligne restent à valider.', 'MOBILE & POINT DE VENTE', 'Le bon contexte, là où l’on travaille.', 'La consultation terrain et l’encaissement en magasin répondent à des contraintes différentes. La feuille de route les distingue avant de définir leurs interfaces.', [
    ['Un site consultable sur mobile', 'Le site et la démonstration s’adaptent aux petits écrans. Les clients s’affichent dans une liste lisible et le parcours de vente reste utilisable sans réduire une interface de bureau entière. Cela ne constitue pas une application ERP native.'],
    ['Applications Android et iOS · prévues', 'Les usages terrain font partie de la cible produit. Les appareils, fonctions, notifications et versions compatibles seront précisés après développement et essais. Aucune application ni lien de téléchargement n’est annoncé comme disponible.'],
    ['Hors ligne · une cible limitée au POS', 'La capacité hors ligne est envisagée pour certains parcours de point de vente, avec des règles de synchronisation et de gestion des conflits à définir. Elle ne s’étend pas implicitement à tout l’ERP. Caisses, imprimantes et moyens de paiement nécessiteront une validation dédiée.'],
  ], ['Puis-je utiliser tout Gestelyo sans connexion ?', 'Non. Aucun fonctionnement ERP complet hors ligne n’est annoncé. Le hors ligne concerne une cible future du point de vente ; il n’est pas implémenté dans cette démonstration.'], ['/secteurs/retail-ecommerce/', '/demo/', '/integrations/']),
  '/personnalisation/': page('Rôles et personnalisation des parcours ERP | Gestelyo', 'Découvrez les règles de personnalisation envisagées dans Gestelyo : rôles, champs et validations. Définissez vos besoins avant les développements spécifiques.', 'PERSONNALISATION & CONTRÔLE', 'Adapter le travail. Garder des règles communes.', 'Une équipe commerciale et une personne chargée des règlements n’ont pas les mêmes responsabilités. Le parcours doit les aider à travailler ensemble sans confondre leurs droits.', [
    ['Commencer par les rôles', 'Identifiez qui consulte, prépare, approuve et exécute chaque opération. Le périmètre avancé prévoit des permissions adaptées ; les règles de séparation entre sociétés et les limites exactes restent à préciser.'],
    ['Définir les validations utiles', 'Une approbation doit porter sur un document précis et une version précise. La démonstration illustre cette règle avec un devis : changer la quantité impose un nouvel accord. Le futur service devra tracer l’auteur, le contexte et le résultat des actions.'],
    ['Distinguer configuration et développement', 'Champs, modèles et tableaux de bord font partie des besoins à étudier. Une connexion spécifique ou une nouvelle logique métier peut nécessiter un projet distinct. Aucun développement illimité n’est inclus dans les forfaits présentés.'],
  ], ['Puis-je automatiser toutes les validations ?', 'Les règles doivent être définies selon les risques et les responsabilités. Les paiements, coordonnées bancaires, droits d’administration et opérations sensibles conservent une validation humaine dans la cible produit.'], ['/intelligence-artificielle/', '/securite/', '/contact/']),
};

const editions = [
  ['construction', 'Construction', 'ERP pour la construction | Édition prévue Gestelyo', 'Préparez le suivi des affaires, budgets et achats de chantier. Découvrez l’édition Construction prévue dans la feuille de route Gestelyo.', 'Les affaires et les coûts, chantier par chantier.', 'L’édition Construction est prévue après le socle commerce et distribution. Elle vise un suivi par affaire, avec un contexte commun pour les engagements et les dépenses.', [
    ['Structurer une affaire', 'Le périmètre envisagé rattache les documents, budgets et responsabilités à un chantier. L’objectif est de distinguer les engagements commerciaux des coûts réellement constatés.'],
    ['Rapprocher achats et besoins terrain', 'Affecter les achats et les réceptions au bon chantier doit aider à expliquer les écarts. Quantités prévues, reçues et utilisées ne doivent pas être confondues.'],
    ['Préparer le périmètre avant disponibilité', 'Les méthodes de calcul, étapes de validation et documents spécifiques seront définis avec les usages métier. La démo actuelle ne gère ni chantier réel ni situations de travaux.'],
  ], ['Un exemple de besoin', 'Une commande de matériaux de 8 000 DH HT doit être affectée au chantier concerné, puis rapprochée des réceptions. Ce scénario décrit une cible, pas une fonction livrée.']],
  ['retail-ecommerce', 'Retail & e-commerce', 'ERP retail et e-commerce | Édition prévue Gestelyo', 'Découvrez les usages prévus pour les magasins et le e-commerce : commandes, stocks partagés et point de vente. Édition future Gestelyo.', 'Les canaux changent. Le stock reste le même.', 'L’édition Retail & e-commerce est prévue après Construction. Elle vise à coordonner les ventes en magasin et à distance, avec des règles de disponibilité communes.', [
    ['Partager les disponibilités entre canaux', 'Une commande en ligne et une vente en magasin peuvent solliciter le même article. Le périmètre cible doit définir la réservation, les délais de synchronisation et la gestion des conflits.'],
    ['Organiser le point de vente', 'Le parcours POS prévu distingue panier, encaissement, retours et clôture. Les périphériques et moyens de paiement seront annoncés seulement après validation.'],
    ['Connecter sans présumer des compatibilités', 'Les connexions aux plateformes e-commerce et aux transporteurs restent à étudier. Les comptes et contrats externes appartiennent à votre entreprise. Aucun connecteur ni mode hors ligne n’est livré dans l’aperçu.'],
  ], ['Un stock, deux canaux', 'Sur 12 unités disponibles, une réservation en ligne de 2 unités laisse 10 unités vendables. La règle de synchronisation devra éviter une vente concurrente sur ces mêmes unités.']],
  ['fabrication', 'Fabrication', 'ERP pour la fabrication | Édition future Gestelyo', 'Explorez les besoins visés par l’édition Fabrication Gestelyo : nomenclatures, matières et suivi de production. Périmètre futur à définir.', 'Relier ce qui entre à ce qui est produit.', 'L’édition Fabrication vient après Services dans la feuille de route. Elle étendrait le socle de gestion aux matières et opérations de production.', [
    ['Décrire les besoins matière', 'Les nomenclatures prévues devront préciser les composants et unités nécessaires à un produit. Les versions et quantités de référence sont essentielles pour expliquer les besoins.'],
    ['Distinguer prévision et consommation', 'Les quantités prévues ne décrivent pas toujours les consommations réelles. Le parcours cible doit tracer les écarts, les pertes éventuelles et les mouvements de stock concernés.'],
    ['Valider les règles avant de planifier', 'Ordres de fabrication, capacité, valorisation et contrôles qualité nécessitent un périmètre métier dédié. La démo commerce n’est pas un outil de planification industrielle et aucune date de disponibilité n’est annoncée.'],
  ], ['Un besoin à définir', 'Un lot de 10 produits exige 20 composants selon sa nomenclature. La cible doit distinguer ces 20 unités prévues des unités réellement consommées et validées.']],
];
for (const [slug, label, title, description, heading, intro, sections, example] of editions) {
  refonteContent[`/secteurs/${slug}/`] = page(title, description, `ÉDITION · ${label.toUpperCase()}`, heading, intro, sections, ['Cette édition est-elle disponible ?', 'Non. Cette page décrit une édition prévue. Le premier périmètre vise le commerce et la distribution ; les fonctions, conditions et dates des autres éditions seront précisées après validation.'], ['/secteurs/', '/secteurs/commerce-distribution/', '/contact/'], { layout: 'edition', status: 'Édition prévue · disponibilité non annoncée', example });
}

export function applyRefonte(content) {
  Object.assign(content, refonteContent);
  const moduleLinks = ['/modules/crm/', '/modules/ventes-facturation/', '/modules/achats/', '/modules/gestion-stock/', '/modules/finance/'];
  Object.assign(content['/modules/'], { title: 'Modules ERP pour PME | CRM, ventes, achats, stock, finance Gestelyo', description: 'Découvrez le socle Gestelyo pour les PME de commerce : CRM, ventes, achats, stocks et finance opérationnelle. Périmètres, exemples et statuts du produit.', intro: 'Le premier périmètre de Gestelyo vise le commerce et la distribution. Cinq domaines reliés forment le socle ; les fonctions avancées et les éditions métier se construisent progressivement.', sections: content['/modules/'].sections.slice(0, 5), sectionLinks: moduleLinks, related: [...moduleLinks, '/tarifs/'], status: 'Socle de lancement prévu · démonstration locale disponible' });
  content['/modules/'].sections[4] = ['Finance · comprendre les échéances', 'Le lancement vise les créances, dettes, flux et exports comptables. La comptabilité native complète est une évolution ultérieure.'];
  Object.assign(content['/produit/'], { status: 'Commerce & distribution en priorité · prototype interactif', intro: 'Gestelyo est un projet d’ERP pour les PME au Maroc. Son premier périmètre relie CRM, ventes, achats, stock et finance opérationnelle pour les entreprises de commerce et de distribution.', related: ['/demo/', '/modules/', '/intelligence-artificielle/', '/migration/', '/tarifs/'], question: ['Que peut-on tester aujourd’hui ?', 'Un tableau de bord conciliable, six fiches clients fictives et un parcours de vente du devis au règlement. Les actions restent locales ; elles ne créent ni compte ERP ni paiement réel.'] });
  const editionLinks = ['/secteurs/commerce-distribution/', '/secteurs/construction/', '/secteurs/retail-ecommerce/', '/secteurs/services-agences/', '/secteurs/fabrication/'];
  Object.assign(content['/secteurs/'], { title: 'Éditions métier ERP | Commerce et feuille de route Gestelyo', description: 'Commerce et distribution en priorité, puis Construction, Retail, Services et Fabrication. Découvrez le périmètre et le statut des éditions Gestelyo.', intro: 'Un socle de gestion commun, puis des parcours adaptés à chaque métier. Le commerce et la distribution constituent la priorité de lancement ; les éditions suivantes sont prévues dans cet ordre.', sections: [['01 · Commerce & distribution', 'Priorité de lancement : clients, devis, commandes, achats, stocks et échéances. La démo illustre un parcours de vente complet.'], ['02 · Construction', 'Édition prévue : affaires, budgets et coûts de chantier.'], ['03 · Retail & e-commerce', 'Édition prévue : coordination des canaux et point de vente.'], ['04 · Services & agences', 'Édition prévue : missions, engagements et rentabilité des prestations.'], ['05 · Fabrication', 'Édition future : nomenclatures, matières et opérations de production.']], sectionLinks: editionLinks, related: ['/modules/', '/tarifs/', '/contact/'], status: 'Feuille de route métier · aucune date ferme annoncée' });
  Object.assign(content['/secteurs/services-agences/'], { status: 'Édition prévue après Retail & e-commerce', intro: 'L’édition Services & agences est prévue après Retail & e-commerce. Elle vise à relier propositions, missions, dépenses et revenus. Elle ne constitue pas le premier périmètre de lancement.', sections: [['Préparer la relation commerciale', 'Le socle CRM et ventes fournit le contexte client. L’édition Services étendrait ce suivi aux engagements d’une mission et aux personnes responsables.'], ['Relier le projet à ses documents', 'La cible rapproche livrables, dépenses et revenus pour comprendre l’avancement et la rentabilité d’une mission. Les méthodes de calcul devront être documentées.'], ['Un périmètre encore à définir', 'Le suivi de projet métier n’est pas démontré dans cet aperçu. Les capacités, l’édition et les conditions commerciales seront précisées avant leur disponibilité.']] });
  Object.assign(content['/secteurs/commerce-distribution/'], { status: 'Priorité de lancement · parcours démontrable', question: ['Gestelyo prévoit-il plusieurs sociétés ?', 'Le multi-société fait partie de la cible d’architecture. Les limites, la séparation des données et les règles de facturation restent à définir ; la démo utilise une seule société fictive.'], related: ['/modules/crm/', '/modules/achats/', '/modules/gestion-stock/', '/modules/finance/', '/demo/'] });
  content['/modules/gestion-stock/'].example = ['La réservation précède la sortie', 'La démo part de 100 unités physiques. Une réservation de 10 laisse 90 disponibles et 100 présentes. La livraison laisse ensuite 90 présentes et libère la réservation : 90 restent disponibles.'];
  content['/modules/ventes-facturation/'].example = ['Des documents conciliables', 'Dans la démo, 10 kits à 250 DH HT représentent 2 500 DH HT et 3 000 DH TTC avec le taux pédagogique de 20 %. Le devis, la commande, la livraison et la facture gardent ce même montant.'];
  content['/demo/'].description = 'Testez le prototype ERP Gestelyo : tableau de bord, filtres CRM et vente du devis au paiement. Données fictives et actions locales, sans compte réel.';
}
