import React, { useEffect, useReducer, useRef, useState } from 'react';
import { ChartBar, Users, Receipt, ArrowRight, ArrowCounterClockwise, MagnifyingGlass, Bell, Check, X } from '@phosphor-icons/react';
import { Logo } from './SiteShell.jsx';
import { money, clients, invoices, months, steps, initialSale, saleReducer, saleTotals, saleInvoice, totalsFor } from './demo-data.mjs';

const clientName = id => clients.find(client => client.id === id)?.name;
const amount = value => `${money(value)} DH`;
function RevenueChart({ month, sales }) {
  const data = months.filter(([key]) => key <= month).map(([key, label]) => ({ label, ...totalsFor(key, sales) }));
  const x = i => 44 + i * 500 / (data.length - 1);
  const y = value => 167 - value / 100000 * 140;
  const series = [['revenue', 'Ventes HT', '#075dcc'], ['purchases', 'Achats HT', '#7368c7'], ['cash', 'Flux net TTC', '#008f9c']];
  return <div className="gd-panel gd-chart"><div className="gd-panel-head"><h3>Évolution de l’activité</h3><span>DH · juin à {month === '2026-10' ? 'octobre' : 'septembre'} 2026</span></div>
    <svg viewBox="0 0 570 205" role="img" aria-label="Évolution des ventes, achats et flux nets. Valeurs exactes dans le tableau sous le graphique.">
      {[0, 25000, 50000, 75000, 100000].map(value => <g key={value}><line x1="44" x2="550" y1={y(value)} y2={y(value)} stroke="#eaf0f7" /><text x="3" y={y(value) + 3} fontSize="9" fill="#61718b">{value / 1000}k</text></g>)}
      <polygon points={`44,167 ${data.map((row, i) => `${x(i)},${y(row.revenue)}`).join(' ')} ${x(data.length - 1)},167`} fill="#075dcc" opacity=".055" />
      {series.map(([key, label, color]) => <g key={key}><polyline points={data.map((row, i) => `${x(i)},${y(row[key])}`).join(' ')} fill="none" stroke={color} strokeWidth="2.5" />{data.map((row, i) => <circle key={i} cx={x(i)} cy={y(row[key])} r="3.5" fill={color}><title>{`${row.label} · ${label} : ${amount(row[key])}`}</title></circle>)}</g>)}
      {data.map((row, i) => <text key={row.label} x={x(i)} y="193" textAnchor="middle" fontSize="10" fill="#61718b">{row.label}</text>)}
    </svg><div className="gd-legend">{series.map(([key, label, color]) => <span key={key}><i style={{ background: color }} />{label}</span>)}</div>
    <details className="gd-chart-values"><summary>Consulter les valeurs</summary><div className="gd-scroll"><table><caption className="sr-only">Montants mensuels de la démonstration</caption><thead><tr><th>Mois</th>{series.map(([key, label]) => <th key={key}>{label}</th>)}</tr></thead><tbody>{data.map(row => <tr key={row.label}><th>{row.label}</th>{series.map(([key]) => <td key={key}>{amount(row[key])}</td>)}</tr>)}</tbody></table></div></details>
  </div>;
}
function InvoiceList({ rows, onClient }) {
  return <div className="gd-panel"><div className="gd-panel-head"><h3>Factures de la période</h3><span>{rows.length} documents</span></div><div className="gd-invoices">{rows.map(row => <button key={row.id} onClick={() => onClient(row.client)}><span className="gd-document"><Receipt size={17} /></span><span><strong>{row.id}</strong><small>{clientName(row.client)}</small></span><span><strong>{amount(row.ht * 1.2)}</strong><small className={`gd-status ${row.paid >= row.ht * 1.2 ? 'paid' : 'pending'}`}>{row.paid >= row.ht * 1.2 ? 'Payée' : row.paid ? 'Partielle' : 'À régler'}</small></span></button>)}</div></div>;
}

export default function DemoWorkspace({ compact = false }) {
  const [view, setView] = useState('dashboard');
  const [month, setMonth] = useState('2026-10');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('Tous');
  const [city, setCity] = useState('Toutes');
  const [owner, setOwner] = useState('Tous');
  const [page, setPage] = useState(0);
  const [selected, setSelected] = useState([]);
  const [detail, setDetail] = useState(null);
  const [alerts, setAlerts] = useState(false);
  const [sale, dispatch] = useReducer(saleReducer, undefined, initialSale);
  const dialog = useRef(null);
  useEffect(() => { if (detail) dialog.current?.showModal(); }, [detail]);
  const allSales = [...invoices, ...saleInvoice(sale)];
  const total = totalsFor(month, allSales);
  const rows = allSales.filter(row => row.month === month);
  const quantities = saleTotals(sale);
  const filtered = clients.filter(client => `${client.name} ${client.id}`.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')) && (status === 'Tous' || status === client.status) && (city === 'Toutes' || city === client.city) && (owner === 'Tous' || owner === client.owner));
  const visible = filtered.slice(page * 4, page * 4 + 4);
  const navigate = next => { setView(next); setAlerts(false); };
  const openClient = id => setDetail(clients.find(client => client.id === id));
  const exportSelection = () => {
    const content = 'Référence;Client;Ville;Statut\n' + clients.filter(client => selected.includes(client.id)).map(client => [client.id, client.name, client.city, client.status].join(';')).join('\n');
    const url = URL.createObjectURL(new Blob(['\uFEFF', content], { type: 'text/csv;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = 'clients-fictifs-gestelyo.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className={`gd-workspace ${compact ? 'gd-compact' : ''}`}>
    <aside className="gd-sidebar"><a href="/" aria-label="Gestelyo, accueil"><Logo /></a><span className="gd-workspace-name">COMMERCE · DÉMO</span>
      {compact ? <nav aria-label="Aperçu des modules"><a className="active" href="/demo/"><ChartBar size={17} />Tableau de bord</a><a href="/modules/crm/"><Users size={17} />CRM</a><a href="/modules/ventes-facturation/"><Receipt size={17} />Ventes</a><a href="/modules/achats/">Achats</a><a href="/modules/gestion-stock/">Stock</a><a href="/modules/finance/">Finance</a></nav> : <nav aria-label="Vues de la démonstration">{[['dashboard', 'Tableau de bord', ChartBar], ['crm', 'Clients', Users], ['sale', 'Parcours de vente', Receipt]].map(([key, label, Icon]) => <button key={key} aria-pressed={view === key} className={view === key ? 'active' : ''} onClick={() => navigate(key)}><Icon size={18} />{label}</button>)}</nav>}
      <div className="gd-sidebar-note"><span className="gd-dot" />Données fictives<br /><small>Aucun compte réel</small></div>
    </aside>
    <div className="gd-body"><div className="gd-topbar"><span>Société Exemple <small>· Casablanca</small></span><div>{!compact && <button aria-label="Afficher les alertes" aria-expanded={alerts} onClick={() => setAlerts(!alerts)}><Bell size={19} /></button>}<span className="gd-avatar">AD</span><span>Admin<small> Espace démo</small></span></div></div>
      {alerts && <div className="gd-alert-pop" role="status"><strong>{rows.filter(row => row.paid < row.ht * 1.2).length} facture(s) à suivre</strong><p>Solde à encaisser sur la période : {amount(total.receivables)} TTC.</p></div>}
      <div className="gd-content"><div className="gd-heading"><div><span className="gd-breadcrumb">Espace de gestion / {view === 'crm' ? 'CRM' : view === 'sale' ? 'Ventes' : 'Vue d’ensemble'}</span><h2>{view === 'crm' ? 'Clients' : view === 'sale' ? 'Du devis au paiement' : 'Tableau de bord'}</h2></div>{view !== 'sale' && <label><span className="sr-only">Période des indicateurs</span><select value={month} onChange={event => setMonth(event.target.value)}><option value="2026-10">Octobre 2026</option><option value="2026-09">Septembre 2026</option></select></label>}</div>
      {view === 'dashboard' && <><div className="gd-metrics">{[['Chiffre d’affaires HT', total.revenue], ['Achats HT', total.purchases], ['Créances clients TTC', total.receivables], ['Dettes fournisseurs TTC', total.payables]].map(([label, value], i) => <div key={label}><span className="gd-metric-label">{label}<ChartBar size={16} /></span><strong>{money(value)} <small>DH</small></strong><span className="gd-metric-note">{i < 2 ? 'Facturé sur la période' : 'Solde des documents de la période'}</span></div>)}</div>
        <div className="gd-dashboard-grid"><RevenueChart month={month} sales={allSales} /><InvoiceList rows={rows} onClient={openClient} /></div>
        <div className="gd-dashboard-bottom"><div className="gd-panel"><div className="gd-panel-head"><h3>Flux des règlements</h3><span>Période sélectionnée</span></div><strong className="gd-cash">{amount(total.cash)} <small>TTC</small></strong><p>Flux net des règlements de la période, sans solde d’ouverture.</p></div><div className="gd-panel gd-next"><span className="gd-dot" /><h3>Une vente, un fil continu.</h3><p>Devis, stock, livraison et règlement.</p>{compact ? <a href="/demo/">Essayer le parcours <ArrowRight size={15} /></a> : <button onClick={() => navigate('sale')}>Préparer une vente <ArrowRight size={15} /></button>}</div></div>
        {!compact && <details className="gd-definitions"><summary>Comment lire ces indicateurs ?</summary><p>CA = factures HT de la période. Créances = TTC facturé moins règlements de ces factures. Dettes = TTC achats moins règlements fournisseurs de la période. TVA pédagogique de 20 % pour cet exemple uniquement. La simulation ajoute une facture d’octobre après l’étape Facture ; son règlement modifie ensuite les créances et le flux net.</p></details>}
      </>}
      {view === 'crm' && <><p className="gd-view-intro">Le contexte commercial de chaque client. Les montants suivent la période sélectionnée.</p><div className="gd-filters"><label className="gd-search"><MagnifyingGlass size={17} /><input value={query} placeholder="Rechercher un client…" aria-label="Rechercher un client" onChange={event => { setQuery(event.target.value); setPage(0); }} /></label>{[['Statut', status, setStatus, ['Tous', 'Actif', 'Prospect', 'En pause']], ['Ville', city, setCity, ['Toutes', 'Casablanca', 'Rabat', 'Marrakech', 'Tanger']], ['Commercial', owner, setOwner, ['Tous', 'Nadia', 'Youssef']]].map(([label, value, setter, options]) => <label key={label}>{label}<select value={value} onChange={event => { setter(event.target.value); setPage(0); }}>{options.map(option => <option key={option}>{option}</option>)}</select></label>)}</div>
        <div className="gd-selection"><span role="status">{selected.length} client(s) sélectionné(s)</span><button disabled={!selected.length} onClick={exportSelection}>Exporter la sélection CSV</button><button onClick={() => { setQuery(''); setStatus('Tous'); setCity('Toutes'); setOwner('Tous'); setPage(0); setSelected([]); }}>Réinitialiser les filtres</button></div>
        <div className="gd-clients">{visible.map(client => { const records = rows.filter(row => row.client === client.id); return <article key={client.id}><label className="gd-checkbox"><input type="checkbox" aria-label={`Sélectionner ${client.name}`} checked={selected.includes(client.id)} onChange={event => setSelected(event.target.checked ? [...selected, client.id] : selected.filter(id => id !== client.id))} /></label><span className="gd-client-avatar">{client.initials}</span><button className="gd-client-name" onClick={() => setDetail(client)}><strong>{client.name}</strong><small>{client.id} · {client.city}</small></button><span className="gd-client-owner">{client.owner}<small>Commercial</small></span><span className="gd-client-amount">{amount(records.reduce((sum, row) => sum + row.ht, 0))}<small>CA HT · période</small></span><span className="gd-status">{client.status}</span><button className="gd-client-open" onClick={() => setDetail(client)} aria-label={`Ouvrir ${client.name}`}><ArrowRight size={18} /></button></article>; })}{!visible.length && <p className="gd-empty" role="status">Aucun client ne correspond à ces filtres.</p>}</div>
        <div className="gd-pagination"><span role="status">{filtered.length} résultat(s) · page {page + 1} / {Math.max(1, Math.ceil(filtered.length / 4))}</span><button disabled={page === 0} onClick={() => setPage(page - 1)}>Précédent</button><button disabled={(page + 1) * 4 >= filtered.length} onClick={() => setPage(page + 1)}>Suivant</button></div>
      </>}
      {view === 'sale' && <><div className="gd-flow-intro"><p>Vendez un lot à Atlas Distribution. Chaque étape conserve le même montant et le document précédent.</p><button onClick={() => dispatch({ type: 'reset' })}><ArrowCounterClockwise size={16} />Recommencer</button></div><ol className="gd-stepper" aria-label="Étapes de la vente">{steps.map((step, i) => <li key={step} className={sale.stage === i ? 'current' : sale.stage > i ? 'done' : ''} aria-current={sale.stage === i ? 'step' : undefined}><span>{sale.stage > i ? <Check size={14} /> : i + 1}</span>{step}</li>)}</ol>
        <div className="gd-sale-grid"><div className="gd-panel gd-sale-document"><div className="gd-panel-head"><div><span className="gd-breadcrumb">ATLAS DISTRIBUTION · CL 001</span><h3>{sale.stage < 2 ? 'DEV 041' : sale.stage < 4 ? 'CMD 041' : sale.stage === 4 ? 'BL 041' : 'FAC DEMO 041'}</h3></div><span className="gd-status">{steps[sale.stage]} · v{sale.version}</span></div><div className="gd-line-item"><span><strong>Kit de fournitures · ART 001</strong><small>Prix unitaire : 250 DH HT</small></span><label>Quantité<input aria-label="Quantité du devis" type="number" min="1" max="100" value={sale.quantity} disabled={sale.stage > 1} onChange={event => dispatch({ type: 'quantity', value: Number(event.target.value) })} /></label></div><dl className="gd-totals"><div><dt>Total HT</dt><dd>{amount(quantities.ht)}</dd></div><div><dt>TVA de l’exemple · 20 %</dt><dd>{amount(quantities.tax)}</dd></div><div><dt>Total TTC</dt><dd>{amount(quantities.ttc)}</dd></div></dl><p className="gd-stage-note" role="status">{['Le devis est prêt. Simulez l’accord du client pour poursuivre.', 'Accord enregistré pour cette version. Modifier la quantité impose un nouvel accord.', 'Commande créée, stock encore non réservé.', 'Stock réservé : les unités restent physiquement présentes.', 'Livraison enregistrée : le stock physique diminue.', 'Facture ajoutée au tableau de bord d’octobre. Aucun règlement enregistré.', 'Règlement fictif enregistré. Le solde de cette facture est nul.'][sale.stage]}</p>{sale.stage < 6 ? <button className="button primary" onClick={() => dispatch({ type: 'next' })}>{['Simuler l’accord client', 'Créer la commande', 'Réserver le stock', 'Simuler la livraison', 'Créer la facture', 'Simuler le règlement'][sale.stage]}<ArrowRight size={17} /></button> : <button className="button primary" onClick={() => { setMonth('2026-10'); navigate('dashboard'); }}>Voir le tableau de bord<ArrowRight size={17} /></button>}<small className="gd-local-note">Simulation locale · aucun document envoyé, aucun paiement exécuté.</small></div>
          <div className="gd-sale-context"><div className="gd-panel"><h3>Stock · entrepôt Casablanca</h3><dl className="gd-stock">{[['Physique', quantities.physical], ['Réservé', quantities.reserved], ['Disponible', quantities.available]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value} unités</dd></div>)}</dl></div><div className="gd-panel"><h3>Deux suivis distincts</h3><p>Livraison : <strong>{sale.stage >= 4 ? 'Effectuée' : 'À effectuer'}</strong></p><p>Paiement : <strong>{sale.stage === 6 ? 'Réglé' : sale.stage >= 5 ? 'À encaisser' : 'Non facturé'}</strong></p></div><div className="gd-panel"><h3>Historique du parcours</h3><ol className="gd-history">{sale.history.map((event, i) => <li key={i}>{event}</li>)}</ol></div></div></div>
      </>}
      </div><div className="gd-disclosure">Prototype interactif · données et entreprises fictives{compact && <a href="/demo/">Ouvrir la démonstration ↗</a>}</div>
    </div>
    <dialog className="gd-dialog" ref={dialog} onClose={() => setDetail(null)} onClick={event => { if (event.target === dialog.current) dialog.current.close(); }} aria-labelledby="gd-client-title">{detail && <><button className="gd-dialog-close" onClick={() => dialog.current.close()} aria-label="Fermer la fiche client"><X size={22} /></button><span className="eyebrow">FICHE CLIENT · DONNÉES FICTIVES</span><h2 id="gd-client-title">{detail.name}</h2><p>{detail.id} · {detail.city} · {detail.owner}</p><p>Statut : <strong>{detail.status}</strong></p><h3>Documents · {month === '2026-10' ? 'octobre' : 'septembre'} 2026</h3>{rows.filter(row => row.client === detail.id).map(row => <div className="gd-client-doc" key={row.id}><strong>{row.id}</strong><span>{amount(row.ht * 1.2)} TTC</span><small>Solde : {amount(row.ht * 1.2 - row.paid)}</small></div>)}{!rows.some(row => row.client === detail.id) && <p>Aucun document sur cette période.</p>}<a href="/modules/crm/">Comprendre le périmètre CRM →</a></>}</dialog>
  </div>;
}
